#!/usr/bin/env python

# version 1.3.1 - 2019-07-20

import subprocess
import re

session = subprocess.Popen(["cat", "/proc/cpuinfo"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
stdout, stderr = session.communicate()

# get Hardware
searchObj = re.search( r'Hardware\s*:\s*(.*)', stdout)
if searchObj:
    rpi_hardware = searchObj.group(1)
else:
    print "Error"

# get Revision
searchObj = re.search( r'Revision\s*:\s*(.*)', stdout)
if searchObj:
    rpi_revision = searchObj.group(1)
else:
    print "Error"

# get Serial
searchObj = re.search( r'Serial\s*:\s*(.*)', stdout)
if searchObj:
    rpi_serial = searchObj.group(1)
else:
    print "Error"

Models = {
    '0015': 'Model A+ (Embest China)', 
    '0014': 'Compute Module (Embest China)', 
    '0013': 'Model B+', 
    '0012': 'Model A+', 
    '0011': 'Compute Module', 
    '0010': 'Model B+', 
    '000d': 'Model B Rev 2', 
    '000e': 'Model B Rev 2', 
    '000f': 'Model B Rev 2', 
    'a22082': 'Pi 3 Model B (Embest China)', 
    '900092': 'Pi Zero v1.2', 
    '900093': 'Pi Zero v1.3', 
    '9000c1': 'Pi Zero W', 
    '0004': 'Model B Rev 2', 
    '0005': 'Model B Rev 2', 
    '0006': 'Model B Rev 2', 
    '0007': 'Model A', 
    '0002': 'Model B Rev 1', 
    '0003': 'Model B Rev 1 ECN0001', 
    '0008': 'Model A', 
    '0009': 'Model A', 
    'a01041': 'Pi 2 Model B v1.1 (Sony UK)', 
    'a02082': 'Pi 3 Model B (Sony UK)',
    'a020d3': 'Pi 3 Model B+ v1.3 (Sony UK)',
    'a22042': 'Pi 2 Model B v1.2', 
    'a21041': 'Pi 2 Model B v1.1 (Embest China)',
    'a03111': 'Pi 4 Model B v1.1 (Sony UK)',
    'b03111': 'Pi 4 Model B v1.1 (Sony UK)',
    'c03111': 'Pi 4 Model B v1.1 (Sony UK)',
}
try:
    rpi_model = Models[rpi_revision]
except:
    rpi_model = 'unknown'

Ram = {
    '0015': '512MB', 
    '0014': '512MB', 
    '0013': '512MB', 
    '0012': '256MB', 
    '0011': '512MB', 
    '0010': '512MB', 
    '000d': '512MB', 
    '000e': '512MB', 
    '000f': '512MB', 
    'a22082': '1GB', 
    '900092': '512MB', 
    '900093': '512MB', 
    '9000c1': '512MB', 
    '0004': '256MB', 
    '0005': '256MB', 
    '0006': '256MB', 
    '0007': '256MB', 
    '0002': '256MB', 
    '0003': '256MB', 
    '0008': '256MB', 
    '0009': '256MB', 
    'a01041': '1GB', 
    'a02082': '1GB',
    'a020d3': '1GB',
    'a22042': '1GB', 
    'a21041': '1GB',
    'a03111': '1GB',
    'b03111': '2GB',
    'c03111': '4GB',
}

try:
    rpi_ram = Ram[rpi_revision]
except:
    rpi_ram = 'unknown'
    
print "Model    :", rpi_model
print "RAM Size :", rpi_ram
print "Hardware :", rpi_hardware
print "Revision :", rpi_revision
print "Serial   :", rpi_serial
